### ISSUE TITLE
Questions about caps lock...

### ISSUE THREAD

**Issue by AllCheeks** [tuconnaisyouknow/BadUSB_adminAccountCreator#1]
Hello, excuse me
How can I keep him in lowercase
uppercase commands cannot be run

example:
Keyboard.print("hello");
But the output Notepad becomes
HELLO

**Comment by tuconnaisyouknow** [comment]
> Hello, excuse me
> 
> How can I keep him in lowercase
> 
> uppercase commands cannot be run
> 
> 
> 
> example:
> 
> Keyboard.print("hello");
> 
> But the output Notepad becomes
> 
> HELLO 
> 
> 

Hello, you have to turn off caps lock off before running the script.

**Comment by AllCheeks** [comment]
If the keyboard is in lowercase, how to solve it

**Comment by tuconnaisyouknow** [comment]
> If the keyboard is in lowercase, how to solve it

If your keyboard is in lowercase it should write in lowercase, i never had this problem.
I'm sorry but i can't help you.

**Comment by AllCheeks** [comment]
ok thank you
